export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const SHOW_ERROR_DIALOG = 'SHOW_ERROR_DIALOG'
export const HIDE_ERROR_DIALOG = 'HIDE_ERROR_DIALOG'

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'

export const JWT_REQUEST = 'JWT_REQUEST'
export const JWT_SUCCESS = 'JWT_SUCCESS'
export const JWT_FAILURE = 'JWT_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const TELEGRAM_REQUEST = 'TELEGRAM_REQUEST'
export const TELEGRAM_SUCCESS = 'TELEGRAM_SUCCESS'
export const TELEGRAM_FAILURE = 'TELEGRAM_FAILURE'

export const TELEGRAM_UPDATE_REQUEST = 'TELEGRAM_UPDATE_REQUEST'
export const TELEGRAM_UPDATE_SUCCESS = 'TELEGRAM_UPDATE_SUCCESS'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE'

export const USER_FUND_REQUEST = 'USER_FUND_REQUEST'
export const USER_FUND_SUCCESS = 'USER_FUND_SUCCESS'
export const USER_FUND_FAILURE = 'USER_FUND_FAILURE'

export const GET_LOCALE_REQUEST = 'GET_LOCALE_REQUEST'
export const SELECT_LOCALE_REQUEST = 'SELECT_LOCALE_REQUEST'

export const GET_COUNTRY_CODE_REQUEST = 'GET_COUNTRY_CODE_REQUEST'
export const CHANGE_COUNTRY_CODE_REQUEST = 'CHANGE_COUNTRY_CODE_REQUEST'

export const CHANNEL_LIST_REQUEST = 'CHANNEL_LIST_REQUEST'
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS'
export const CHANNEL_LIST_FAILURE = 'CHANNEL_LIST_FAILURE'

export const CHANNEL_ADD_REQUEST = 'CHANNEL_ADD_REQUEST'
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS'
export const CHANNEL_ADD_FAILURE = 'CHANNEL_ADD_FAILURE'

export const ADZONE_LIST_REQUEST = 'ADZONE_LIST_REQUEST'
export const ADZONE_LIST_SUCCESS = 'ADZONE_LIST_SUCCESS'
export const ADZONE_LIST_FAILURE = 'ADZONE_LIST_FAILURE'

export const ADZONE_ADD_REQUEST = 'ADZONE_ADD_REQUEST'
export const ADZONE_ADD_SUCCESS = 'ADZONE_ADD_SUCCESS'
export const ADZONE_ADD_FAILURE = 'ADZONE_ADD_FAILURE'

export const AIRDROP_LIST_REQUEST = 'AIRDROP_LIST_REQUEST'
export const AIRDROP_LIST_SUCCESS = 'AIRDROP_LIST_SUCCESS'
export const AIRDROP_LIST_FAILURE = 'AIRDROP_LIST_FAILURE'

export const AIRDROP_GET_REQUEST = 'AIRDROP_GET_REQUEST'
export const AIRDROP_GET_SUCCESS = 'AIRDROP_GET_SUCCESS'
export const AIRDROP_GET_FAILURE = 'AIRDROP_GET_FAILURE'

export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST'
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS'
export const PROMOTION_LIST_FAILURE = 'PROMOTION_LIST_FAILURE'

export const PROMOTION_GET_REQUEST = 'PROMOTION_GET_REQUEST'
export const PROMOTION_GET_SUCCESS = 'PROMOTION_GET_SUCCESS'
export const PROMOTION_GET_FAILURE = 'PROMOTION_GET_FAILURE'

export const REDPACKET_LIST_REQUEST = 'REDPACKET_LIST_REQUEST'
export const REDPACKET_LIST_SUCCESS = 'REDPACKET_LIST_SUCCESS'
export const REDPACKET_LIST_FAILURE = 'REDPACKET_LIST_FAILURE'

export const REDPACKET_GET_REQUEST = 'REDPACKET_GET_REQUEST'
export const REDPACKET_GET_SUCCESS = 'REDPACKET_GET_SUCCESS'
export const REDPACKET_GET_FAILURE = 'REDPACKET_GET_FAILURE'

export const GEOIP_REQUEST = 'GEOIP_REQUEST'
export const GEOIP_SUCCESS = 'GEOIP_SUCCESS'
export const GEOIP_FAILURE = 'GEOIP_FAILURE'